package org.drools.workshop;
import org.drools.workshop.model.*;
import java.util.ArrayList;

rule "Nuevo alumno o subir de nivel"
    when
        $u : User( progreso == 0)
        $t : Tema(nivel == $u.nivel)
    then
        $u.setProblema(new ArrayList<>($t.getProblema()));
end

rule "Subir de nivel"
    when
        $u : User(progreso >= 3)
    then
        $u.subirNivel();
        $u.setProgreso(0);
end

rule "Bajar de nivel"
    when    
        $u : User(progreso <= -3)
    then
        $u.bajarNivel();
        $u.setProgreso(0);
end